### ISSUE TITLE
关于画质改善

### ISSUE THREAD

**Issue by zly2006** [wangwc18/mygoFlaskProject#1]
我这里有大会员画质的前3集，应该比大佬那边you-get的画质要好，已转码合并成mp4，请问是否需要？
别问为什么只下载了前三集，本来想着随看随下结果没空

**Comment by zly2006** [comment]
```
total 5986960
-rwxr-xr-x  1 zhaoliyan  staff   592M 10  1 22:53 1.mp4
-rwxr-xr-x  1 zhaoliyan  staff   690M 10  1 22:53 2.mp4
-rwxr-xr-x  1 zhaoliyan  staff   673M 10  1 22:52 3.mp4
```
每集大小在0.6-0.7GB

**Comment by wangwc18** [comment]
哈哈哈哈，其实我之前逛论坛的时候看见过一些高清资源比如https://bbs.nga.cn/read.php?tid=37814178&page=1&rand=214这个里头就有人分享了一下（有个阿里云盘https://www.aliyundrive.com/s/4vHPUhfMMEK
提取码: ja76，里面的[MgGO_official]「BanG Dream! It's MyGO!!!!!」[简体内封字幕]，差不多就是b站的那个），用小文件主要是方便（其实还好这个视频是v265编码，会比v264老编码小不少），而且不得不吐槽一下，百度云盘最大只能传4个G单个文件还TM限速，阿里云盘不限速但是不能分享压缩包，国内不是所有人都能访问谷歌云盘，所以嘛。。。。。

**Comment by zly2006** [comment]
哈哈哈，那就算了，百度网盘真垃圾
