### ISSUE TITLE
建议作者为这个项目添加一个LICENSE（许可证）

### ISSUE THREAD

**Issue by HappyRespawnanchor** [wangwc18/mygoFlaskProject#10]
https://choosealicense.com/
![图片](https://github.com/wangwc18/mygoFlaskProject/assets/80967824/311553d5-3d7d-4899-9cae-839d1b797b4e)

参考这张图
![图片](https://github.com/wangwc18/mygoFlaskProject/assets/80967824/a40082cc-f69e-4bb5-8f79-4a87158be0f6)

建议给这个项目添加一个LICENSE

**Comment by wangwc18** [comment]
感谢提醒，不过我个人还是喜欢简单MIT协议(通篇没有几个字，适合我这种大聪明)，所以后面我把证书又改成MIT啦，哈哈哈哈哈哈
