### ISSUE TITLE
百度网盘的提取码是不是更改了

### ISSUE THREAD

**Issue by JoecosB** [wangwc18/mygoFlaskProject#15]
我在用readme里面提供的百度网盘提取码的时候发现提取码并不是eyrw，而是点进链接自动填充的那个提取码。

**Comment by wangwc18** [comment]
是的，前几天发现有人把网盘举报了还是怎么的，显示里头的说明txt文件违规，我真无语。。。。所以改了一下链接忘改外面了。。。
