### ISSUE TITLE
请教一下整个项目是怎么做的

### ISSUE THREAD

**Issue by Runninginsilence1** [wangwc18/mygoFlaskProject#18]
我知道视频和弹幕之类的数据可以直接获取，但是页面样式这些是怎么弄的？不会也是靠爬虫爬取的吧，是参考页面样式然后自己写的代码吗？求教

**Comment by wangwc18** [comment]
我是参考页面样式自己写的，应该是有工具能把页面的资源递归下下来，之后你再调整一下就能做出这个网页的静态内容，不过考虑到看这些代码的时间成本，我还是自己造吧。。。
