### ISSUE TITLE
不支持火狐吗

### ISSUE THREAD

**Issue by gopep9** [wangwc18/mygoFlaskProject#3]
火狐一直在转圈
https://i.postimg.cc/Y2WsDtm0/2023-11-20-042825.png
chrome和edge倒是能正常播放

**Comment by gopep9** [comment]
还是说火狐浏览器不支持hevc？

**Comment by wangwc18** [comment]
看了一下确实不支持，原因就是如你所说火狐还没有支持最新的编码格式，我试了一下老编码是可以的，你可以把video文件夹里的视频转一下编码（体积立刻会变大两倍。。。），或者直接下我这个 https://www.alipan.com/s/w1p8wp5K3kZ 
把这个video文件夹下好之后，替换mygoFlaskProject里的video文件夹就行了

**Comment by gopep9** [comment]
刚刷到了这个视频 https://www.bilibili.com/video/BV1Fe411Z7XP 下面的评论说在线的hevc格式也是需要hevc扩展才能正常播放
我用虚拟机试了下假如电脑之前没有装过hevc扩展的话在chrome上也是只有声音的，可能readme加下说明比较好。

**Comment by wangwc18** [comment]
我已经把大多数(包括火狐)浏览器支持的视频源(v264编码)放在README的网盘里了，需要的可以自取
