### ISSUE TITLE
能不能用go语言再写一份

### ISSUE THREAD

**Issue by yebei199** [wangwc18/mygoFlaskProject#7]
不觉得这很酷吗, 很符合我对BanG Dream! It's MyGO!!!!!的想象

**Comment by wangwc18** [comment]
不太擅长go语言，还在学习中。。。。。

**Comment by julyfun** [comment]
幽默~

**Comment by RH-Xie** [comment]
你是否在寻找：
![image](https://github.com/wangwc18/mygoFlaskProject/assets/74254340/e287292f-6d14-49dd-a5f8-21abcdcf334f)
